### ISSUE TITLE
Модифицировать CI для backend

### ISSUE THREAD

**Issue by geogreck** [stewkk/minimal-login-page#16]
К сожалению, не могу это сделать самостоятельно, так как весь CI завязан на make файлах

Код для получения измененных файлов, используемый мною, прилагаю:

```yml
- name: Get file changes
              id: get_file_changes
              uses: trilom/file-changes-action@v1.2.4
              with:
                  output: ' '

            - name: Echo file changes
              id: hello
              run: |
                  echo Added files: ${{ steps.get_file_changes.outputs.files_added }}
                  echo Changed files: ${{ steps.get_file_changes.outputs.files_modified }}
                  echo Removed files: ${{ steps.get_file_changes.outputs.files_removed }}

```
